package com.islesplus.ui;
public final class Metrics {
    private Metrics() {}
    public static final int BEVEL=1, CARD_PAD_X=6, CARD_PAD_Y=6, HEADER_GAP=6, DRAWER_PAD=6, DRAWER_GAP=5, GRID_GAP=6,
        CARET=14, BIG_TOGGLE_W=40, BIG_TOGGLE_H=15, SMALL_TOGGLE_W=24, SMALL_TOGGLE_H=12, MINI_TOGGLE_W=21, MINI_TOGGLE_H=10,
        TILE_H=18, TILE_BOX=10, CHIP_BOX=7, CHIP_H=13, CHIP_PAD_X=5,
        BUTTON_H=16, BUTTON_SMALL_H=13, BUTTON_PAD_X=7, ICON_BUTTON=15,
        FIELD_H=16, SLIDER_H=14, RAIL_H=15, RAIL_THIN_H=12, KNOB_W=7, VALUE_CHIP_W=30, LABEL_COL_W=28,
        ANCHOR_CELL_H=22, ANCHOR_GAP=4, DROPDOWN_H=18, DROPDOWN_ROW_H=16, DROPDOWN_MAX_ROWS=5,
        DIALOG_W=208, DIALOG_TITLE_H=16, TAB_H=20, TAB_GAP=7, LINE_H=10, TITLE_LINE_H=11;
}
